### ISSUE TITLE
module 'jinja2' has no attribute escape

### ISSUE THREAD

**Issue by ryascott** [simonw/datasette-render-binary#4]
datasette==0.63
jinja2==3.1.2

After installing the datasette-render-binary plugin I received the following error when trying to view a table with binary data:

![image](https://user-images.githubusercontent.com/559711/199260324-89c3c7fd-52c2-43b9-9781-e02cdf05ab51.png)

The code that generated the error is below:
https://github.com/simonw/datasette-render-binary/blob/05534ae93079f8dd1eedf2b54e499ff9c6269df5/datasette_render_binary/__init__.py#L42

I believe the change for escape occurred in the 3.10 release of Jinja2

[Jinja2 3.1.0 Changes](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0)

![image](https://user-images.githubusercontent.com/559711/199261358-a3d34176-40d9-4d9a-a06f-afdbeb678410.png)

Thanks
Ryan Scott

**Comment by simonw** [comment]
I just got this too.
